### ISSUE TITLE
Issues with Autopkg 2 - GoToMeeting - GoToMeetingURLProvider

### ISSUE THREAD

**Issue by TSPARR** [autopkg/homebysix-recipes#268]
```
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 820, in get_processor
    _tmp = imp.load_source(processor_name, processor_filename)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/munki/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes/GoToMeeting/GoToMeetingURLProvider.py", line 22, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 820, in get_processor
    _tmp = imp.load_source(processor_name, processor_filename)
Failed.
```

**Comment by homebysix** [comment]
Is it safe to infer that you're using an AutoPkg 2.0 beta?

**Comment by TSPARR** [comment]
Yes, sorry. I put it in the title, but I probably should have mentioned it in the comments as well. Just trying to get the initial info out there as Autopkg 2 is in the release candidate phase with plans to go live next week.

**Comment by homebysix** [comment]
Hi @TSPARR - thanks, just making sure. I've made some tweaks in 90152f9 that should resolve this. Care to have a try?

**Comment by TSPARR** [comment]
Seems to be working correctly for me @homebysix. Thanks!
