### ISSUE TITLE
Royal TSX PKG not working

### ISSUE THREAD

**Issue by killahquam** [autopkg/homebysix-recipes#295]
While the download recipe is working, there seems to be an issue with the package one and its failing.

**Comment by homebysix** [comment]
Can confirm:

```
Processing Royal/RoyalTSX.pkg.recipe...
WARNING: Royal/RoyalTSX.pkg.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
URLTextSearcher: Found matching text (url): https://royaltsx-v4.royalapps.com/updates/royaltsx_4.3.0.1000.dmg
URLDownloader
URLDownloader: Storing new Last-Modified header: Mon, 02 Mar 2020 09:12:53 GMT
URLDownloader: Storing new ETag header: "7c7cfcc072f0d51:0"
URLDownloader: Downloaded ~/Library/AutoPkg/Cache/com.github.homebysix.pkg.RoyalTSX/downloads/royaltsx_4.3.0.1000.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image ~/Library/AutoPkg/Cache/com.github.homebysix.pkg.RoyalTSX/downloads/royaltsx_4.3.0.1000.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /private/tmp/dmg.xLlJei/Royal TSX.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.xLlJei/Royal TSX.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.xLlJei/Royal TSX.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
Versioner
Versioner: Mounted disk image ~/Library/AutoPkg/Cache/com.github.homebysix.pkg.RoyalTSX/downloads/royaltsx_4.3.0.1000.dmg
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/Versioner.py", line 70, in main
    plist = plistlib.load(f)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/plistlib.py", line 950, in load
    return p.parse(fp)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/plistlib.py", line 260, in parse
    self.parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: encoding specified in XML declaration is incorrect: line 1, column 31
```

Looks like the **Royal TSX.app/Contents/Info.plist** file is abnormal in a couple ways, one of which is specifying `encoding="utf-16"` in the XML header. Although that probably doesn't prevent the RoyalTSX app from launching, it does prevent `plistlib` from reading the Info.plist file.

I suggest we wait to see whether the next version of RoyalTSX reverts back to utf-8 as previous versions had. If not, we'd either need to (a) contact the developer and request they switch back to utf-8, or (b) raise the issue with the AutoPkg project maintainers, since it's not unique to this recipe.
