### ISSUE TITLE
Quicksilver.pkg fails trying on AppDmgVersioner processor

### ISSUE THREAD

**Issue by grahampugh** [autopkg/homebysix-recipes#297]
When running the Quicksilver.pkg recipe, we get the following error:

```
AppDmgVersioner
AppDmgVersioner: Mounted disk image /Users/gpugh/Library/AutoPkg/Cache/local.pkg.Quicksilver/downloads/Quicksilver.dmg
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/AppDmgVersioner.py", line 58, in read_bundle_info
    info = plistlib.load(f)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/plistlib.py", line 950, in load
    return p.parse(fp)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/plistlib.py", line 260, in parse
    self.parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 218, column 12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 480, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/AppDmgVersioner.py", line 70, in main
    info = self.read_bundle_info(app_path)
  File "/Library/AutoPkg/autopkglib/AppDmgVersioner.py", line 60, in read_bundle_info
    raise ProcessorError(f"Can't read {plistpath}: {error}")
autopkglib.ProcessorError: Can't read /private/tmp/dmg.tnEZFo/Quicksilver.app/Contents/Info.plist: not well-formed (invalid token): line 218, column 12
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
Can't read /private/tmp/dmg.tnEZFo/Quicksilver.app/Contents/Info.plist: not well-formed (invalid token): line 218, column 12
Failed.
```

I'm not sure what would be wrong with line 218 of `Info.plist`, which is the `string` key here:
```xml
			<key>NSKeyEquivalent</key>
			<dict>
				<key>default</key>
				<string></string>
			</dict>
```

So, not sure how to fix it.

**Comment by grahampugh** [comment]
Aha, so that weird symbol appeared when I submitted the issue - obviously some errant hidden character. I guess that's not really fixable without informing the developers.

**Comment by grahampugh** [comment]
On the other hand, `defaults` and `PlistBuddy` don't have the problem, so it seems to be some problem with the way `AppDmgVersioner` reads the `Info.plist`:

```
$ defaults read /Volumes/Quicksilver/Quicksilver.app/Contents/Info.plist CFBundleShortVersionString
1.6.0

$ /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" /Volumes/Quicksilver/Quicksilver.app/Contents/Info.plist
1.6.0
```

**Comment by homebysix** [comment]
Just taking a look at this — very interesting. That character looks like a unicode "control character," but I'm not sure why it would be in the plist in its raw form.

I think this is a manifestation of plistlib's strictness relative to the old FoundationPlist. In theory, it's something that could be worked around in the AutoPkg core, but I'm not sure it's worth the effort unless the problem becomes widespread.

Might we reach out to the Quicksilver developer and inquire about whether the character can be encoded in a way that works with plistlib?

**Comment by homebysix** [comment]
Worked around in #332, which is working for Quicksilver 1.6.1 for me:

```
% autopkg run -v Quicksilver/Quicksilver.pkg.recipe
Processing Quicksilver/Quicksilver.pkg.recipe...
WARNING: Quicksilver/Quicksilver.pkg.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
URLDownloader: File size returned by webserver matches that of the cached file: 6781343 bytes
URLDownloader: WARNING: Matching a download by filesize is a fallback mechanism that does not guarantee that a build is unchanged.
URLDownloader: Using existing ~/Library/AutoPkg/Cache/com.github.homebysix.pkg.Quicksilver/downloads/Quicksilver.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image ~/Library/AutoPkg/Cache/com.github.homebysix.pkg.Quicksilver/downloads/Quicksilver.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /private/tmp/dmg.TRJqSy/Quicksilver.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.TRJqSy/Quicksilver.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.TRJqSy/Quicksilver.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
FoundationDmgVersioner
FoundationDmgVersioner: Mounted disk image ~/Library/AutoPkg/Cache/com.github.homebysix.pkg.Quicksilver/downloads/Quicksilver.dmg
FoundationDmgVersioner: BundleID: com.blacktree.Quicksilver
FoundationDmgVersioner: Version: 1.6.1
FoundationPkgCreator
FoundationPkgCreator: Mounted disk image ~/Library/AutoPkg/Cache/com.github.homebysix.pkg.Quicksilver/downloads/Quicksilver.dmg
FoundationPkgCreator: Using path '/private/tmp/dmg.gIAIPd/Quicksilver.app' matched from globbed '/private/tmp/dmg.gIAIPd/*.app'.
FoundationPkgCreator: Copied /private/tmp/dmg.gIAIPd/Quicksilver.app to ~/Library/AutoPkg/Cache/com.github.homebysix.pkg.Quicksilver/payload/Applications/Quicksilver.app
FoundationPkgCreator: Connecting
FoundationPkgCreator: Sending packaging request
FoundationPkgCreator: Disconnecting
Receipt written to ~/Library/AutoPkg/Cache/com.github.homebysix.pkg.Quicksilver/receipts/Quicksilver.pkg-receipt-20201113-224930.plist

The following packages were built:
    Identifier                 Version  Pkg Path                                                                                      
    ----------                 -------  --------                                                                                      
    com.blacktree.Quicksilver  1.6.1    ~/Library/AutoPkg/Cache/com.github.homebysix.pkg.Quicksilver/Quicksilver-1.6.1.pkg  
```
