### ISSUE TITLE
bartender munki recipe

### ISSUE THREAD

**Issue by echoparkbaby** [autopkg/homebysix-recipes#319]
would love to have a munki recipe for Bartender

**Comment by homebysix** [comment]
Agreed! Would you like to take a shot at submitting one in a pull request?

**Comment by echoparkbaby** [comment]
I’m green here. Can’t find a how to post a PR request without actually modifying code. But there is no munki recipe so I’m lost.

**Comment by homebysix** [comment]
Solved by #320 and #322. Thanks!

**Comment by echoparkbaby** [comment]
I just updated the repo, recreated the Override and trusted it, but it's giving my Python errors. Running autopkg on other recipes works fine. Here's what I'm getting 

ladmin@swine:~$ autopkg run -vvv Bartender.munki.recipe 
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2887, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2881, in main
    exit(subcommands[verb]["function"](argv))
  File "/usr/local/bin/autopkg", line 2327, in run_recipes
    search_github=make_suggestions,
  File "/usr/local/bin/autopkg", line 430, in load_recipe
    auto_pull=auto_pull,
  File "/usr/local/bin/autopkg", line 430, in load_recipe
    auto_pull=auto_pull,
  File "/usr/local/bin/autopkg", line 430, in load_recipe
    auto_pull=auto_pull,
  [Previous line repeated 982 more times]
  File "/usr/local/bin/autopkg", line 400, in load_recipe
    auto_pull=auto_pull,
  File "/usr/local/bin/autopkg", line 307, in locate_recipe
    recipe_file = find_recipe(name, override_dirs + recipe_dirs)
  File "/usr/local/bin/autopkg", line 205, in find_recipe
    return find_recipe_by_identifier(id_or_name, search_dirs) or find_recipe_by_name(
  File "/Library/AutoPkg/autopkglib/__init__.py", line 318, in find_recipe_by_identifier
    matches = glob.glob(pattern)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/glob.py", line 71, in _iglob
    for dirname in dirs:
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/glob.py", line 72, in _iglob
    for name in glob_in_dir(dirname, basename, dironly):
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/glob.py", line 83, in _glob1
    return fnmatch.filter(names, pattern)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/fnmatch.py", line 51, in filter
    pat = os.path.normcase(pat)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/posixpath.py", line 55, in normcase
    if not isinstance(s, (bytes, str)):
RecursionError: maximum recursion depth exceeded in __instancecheck__
`

**Comment by homebysix** [comment]
@echoparkbaby - Just saw this, but the Bartender.munki recipe works for me on AutoPkg 2.2. Are you still seeing that error?

**Comment by echoparkbaby** [comment]
no errors. working for me. But looks like there will need to be a Bartender4 recipe just for Big Sur. Haven't searched repos to see if one is available yet.
