### ISSUE TITLE
RecordIt.download.recipe

### ISSUE THREAD

**Issue by blackthroat** [autopkg/homebysix-recipes#359]
Since 19b5cd1, I'm receiving this error:

```URLDownloader
{'Input': {'filename': 'RecordIt.zip', 'url': 'https://recordit.co/latest-osx'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 196, in execute_curl
    errors=errors,
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://recordit.co/latest-osx', '--fail', '--output', '/Users/ladmin/Library/AutoPkg/Cache/com.github.homebysix.download.RecordIt/downloads/tmp9vpcsts7']' returned non-zero exit status 60.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 658, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 465, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLDownloader.py", line 328, in main
    raw_headers = self.download_with_curl(curl_cmd)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 204, in download_with_curl
    proc_stdout, proc_stderr, retcode = self.execute_curl(curl_cmd, text)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 199, in execute_curl
    raise ProcessorError(e)
autopkglib.ProcessorError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://recordit.co/latest-osx', '--fail', '--output', '/Users/ladmin/Library/AutoPkg/Cache/com.github.homebysix.download.RecordIt/downloads/tmp9vpcsts7']' returned non-zero exit status 60.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 658, in process
    self.env = processor.process()
Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://recordit.co/latest-osx', '--fail', '--output', '/Users/ladmin/Library/AutoPkg/Cache/com.github.homebysix.download.RecordIt/downloads/tmp9vpcsts7']' returned non-zero exit status 60.
Failed.
```
Visiting `https://recordit.co/latest-osx` with Chrome initiates the download with no problem. Perhaps a `user_agent` needs to be added to the recipe?

**Comment by blackthroat** [comment]
Looks like maybe this a certificate issue.

```
$ curl https://recordit.co/latest-osx
curl: (60) SSL certificate problem: certificate has expired
```

**Comment by homebysix** [comment]
Looks like the developer fixed the cert issue.

```
Processing RecordIt/RecordIt.download.recipe...
WARNING: RecordIt/RecordIt.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing ~/Library/AutoPkg/Cache/com.github.homebysix.download.RecordIt/downloads/RecordIt.zip
EndOfCheckPhase
Unarchiver
Unarchiver: Guessed archive format 'zip' from filename RecordIt.zip
Unarchiver: Unarchived ~/Library/AutoPkg/Cache/com.github.homebysix.download.RecordIt/downloads/RecordIt.zip to ~/Library/AutoPkg/Cache/com.github.homebysix.download.RecordIt/RecordIt/Applications
CodeSignatureVerifier
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: ~/Library/AutoPkg/Cache/com.github.homebysix.download.RecordIt/RecordIt/Applications/RecordIt.app: valid on disk
CodeSignatureVerifier: ~/Library/AutoPkg/Cache/com.github.homebysix.download.RecordIt/RecordIt/Applications/RecordIt.app: satisfies its Designated Requirement
CodeSignatureVerifier: ~/Library/AutoPkg/Cache/com.github.homebysix.download.RecordIt/RecordIt/Applications/RecordIt.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
Versioner
Versioner: Found version 1.6.10 in file ~/Library/AutoPkg/Cache/com.github.homebysix.download.RecordIt/RecordIt/Applications/RecordIt.app/Contents/Info.plist
Receipt written to ~/Library/AutoPkg/Cache/com.github.homebysix.download.RecordIt/receipts/RecordIt.download-receipt-20210102-113155.plist
```
