### ISSUE TITLE
RingCentralMeetings.download.recipe

### ISSUE THREAD

**Issue by blackthroat** [autopkg/homebysix-recipes#381]
From a browser, https://www.ringcentral.com/office/features/online-meetings/video-conferencing.html redirects to https://www.ringcentral.com/video.html

```
URLTextSearcher
{'Input': {'re_pattern': '(dn\\.ringcentral\\.com\\/data\\/web\\/download\\/RCMeetings\\/[\\d]+\\/RCMeetingsClientSetup\\.pkg)',
           'result_output_var_name': 'download_path',
           'url': 'https://www.ringcentral.com/office/features/online-meetings/video-conferencing.html'}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 658, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 465, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 122, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 109, in re_search
    raise ProcessorError(f"{NO_MATCH_MESSAGE}: {self.env['url']}")
autopkglib.ProcessorError: No match found on URL: https://www.ringcentral.com/office/features/online-meetings/video-conferencing.html
  File "/Library/AutoPkg/autopkglib/__init__.py", line 658, in process
    self.env = processor.process()
No match found on URL: https://www.ringcentral.com/office/features/online-meetings/video-conferencing.html
Failed.
```
The RingCentral Meetings package can also be found on https://support.ringcentral.com/download.html (https://downloads.ringcentral.com/RCM/RC/meetings/mac/RCMeetingsClientSetup.pkg)

**Comment by ChefAustin** [comment]
Seeing the same thing over here, too.
```
$ autopkg run -vvvv RingCentralMeetings.munki
Processing RingCentralMeetings.munki...
{'AUTOPKG_VERSION': '2.2',
 'BUNDLE_ID': 'us.zoom.ringcentral',
 'CACHE_DIR': '/Users/Shared/autopkg/Cache',
 'MUNKI_REPO': '/Users/Shared/munki_repo',
 'MUNKI_REPO_SUBDIR': 'applications/RingCentral/RingCentralMeetings',
 'NAME': 'RingCentral Meetings',
 'PARENT_RECIPES': ['/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.homebysix-recipes/RingCentral/RingCentralMeetings.munki.recipe',
                    '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.homebysix-recipes/RingCentral/RingCentralMeetings.pkg.recipe',
                    '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.homebysix-recipes/RingCentral/RingCentralMeetings.download.recipe'],
 'RECIPE_CACHE_DIR': '/Users/Shared/autopkg/Cache/local.munki.RingCentralMeetings',
 'RECIPE_DIR': '/Users/Shared/autopkg/RecipeOverrides',
 'RECIPE_OVERRIDE_DIRS': ['/Users/Shared/autopkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/Shared/autopkg/RecipeOverrides/RingCentralMeetings.munki.recipe',
 'RECIPE_REPOS': {'/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.andrewvalentine-recipes': {'URL': 'https://github.com/autopkg/andrewvalentine-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.apettinen-recipes': {'URL': 'https://github.com/autopkg/apettinen-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.arubdesu-recipes': {'URL': 'https://github.com/autopkg/arubdesu-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.bnpl-recipes': {'URL': 'https://github.com/autopkg/bnpl-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.bochoven-recipes': {'URL': 'https://github.com/autopkg/bochoven-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.chefaustin-recipes': {'URL': 'https://github.com/autopkg/chefaustin-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.chilcote-recipes': {'URL': 'https://github.com/autopkg/chilcote-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.dataJAR-recipes': {'URL': 'https://github.com/autopkg/dataJAR-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.eholtam-recipes': {'URL': 'https://github.com/autopkg/eholtam-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.erikng-recipes': {'URL': 'https://github.com/autopkg/erikng-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.foigus-recipes': {'URL': 'https://github.com/autopkg/foigus-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.gerardkok-recipes': {'URL': 'https://github.com/autopkg/gerardkok-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.gregneagle-recipes': {'URL': 'https://github.com/autopkg/gregneagle-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.hansen-m-recipes': {'URL': 'https://github.com/autopkg/hansen-m-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes': {'URL': 'https://github.com/autopkg/hjuutilainen-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.homebysix-recipes': {'URL': 'https://github.com/autopkg/homebysix-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.its-unibas-recipes': {'URL': 'https://github.com/autopkg/its-unibas-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.jaharmi-recipes': {'URL': 'https://github.com/autopkg/jaharmi-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.jbaker10-recipes': {'URL': 'https://github.com/autopkg/jbaker10-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes': {'URL': 'https://github.com/autopkg/jessepeterson-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.jleggat-recipes': {'URL': 'https://github.com/autopkg/jleggat-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.jlehikoinen-recipes': {'URL': 'https://github.com/autopkg/jlehikoinen-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes': {'URL': 'https://github.com/autopkg/joshua-d-miller-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.keeleysam-recipes': {'URL': 'https://github.com/autopkg/keeleysam-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.killahquam-recipes': {'URL': 'https://github.com/autopkg/killahquam-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.n8felton-recipes': {'URL': 'https://github.com/autopkg/n8felton-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes': {'URL': 'https://github.com/autopkg/nmcspadden-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.novaksam-recipes': {'URL': 'https://github.com/autopkg/novaksam-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.rtrouton-recipes': {'URL': 'https://github.com/autopkg/rtrouton-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes': {'URL': 'https://github.com/autopkg/scriptingosx-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.thenikola-recipes': {'URL': 'https://github.com/autopkg/thenikola-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.timsutton-recipes': {'URL': 'https://github.com/autopkg/timsutton-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.wardsparadox-recipes': {'URL': 'https://github.com/autopkg/wardsparadox-recipes'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.facebook.Recipes-for-AutoPkg': {'URL': 'https://github.com/facebook/Recipes-for-AutoPkg.git'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.hjuutilainen.autopkg-virustotalanalyzer': {'URL': 'https://github.com/hjuutilainen/autopkg-virustotalanalyzer.git'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.notverypc.autopkg-recipes': {'URL': 'https://github.com/notverypc/autopkg-recipes.git'},
                  '/Users/Shared/autopkg/RecipeRepos/com.github.soberhofer.autopkg-recipes': {'URL': 'https://github.com/soberhofer/autopkg-recipes.git'}},
 'RECIPE_REPO_DIR': '/Users/Shared/autopkg/RecipeRepos',
 'RECIPE_SEARCH_DIRS': ['/Users/Shared/autopkg/Recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.hjuutilainen.autopkg-virustotalanalyzer',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.facebook.Recipes-for-AutoPkg',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.notverypc.autopkg-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.soberhofer.autopkg-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.andrewvalentine-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.apettinen-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.arubdesu-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.bnpl-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.bochoven-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.chefaustin-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.chilcote-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.dataJAR-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.eholtam-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.erikng-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.foigus-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.gerardkok-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.gregneagle-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.hansen-m-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.homebysix-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.its-unibas-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.jaharmi-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.jbaker10-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.jleggat-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.jlehikoinen-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.keeleysam-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.killahquam-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.n8felton-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.novaksam-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.rtrouton-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.thenikola-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.timsutton-recipes',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.wardsparadox-recipes',
                        '/Users/Shared/autopkg/RecipeOverrides',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.homebysix-recipes/RingCentral',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.homebysix-recipes/RingCentral',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.homebysix-recipes/RingCentral',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.homebysix-recipes/RingCentral',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.homebysix-recipes/RingCentral',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.homebysix-recipes/RingCentral',
                        '/Users/Shared/autopkg/RecipeRepos/com.github.autopkg.homebysix-recipes/RingCentral'],
 'pkginfo': {'blocking_applications': ['RingCentral Meetings.app'],
             'catalogs': ['alpha'],
             'category': 'Multimedia',
             'description': 'Online videoconferencing app for RingCentral.',
             'developer': 'RingCentral',
             'display_name': 'RingCentral Meetings',
             'minimum_os_version': '10.10',
             'name': 'RingCentral Meetings',
             'unattended_install': True,
             'unattended_uninstall': True},
 'verbose': 4}
URLTextSearcher
{'Input': {'re_pattern': '(dn\\.ringcentral\\.com\\/data\\/web\\/download\\/RCMeetings\\/[\\d]+\\/RCMeetingsClientSetup\\.pkg)',
           'result_output_var_name': 'download_path',
           'url': 'https://www.ringcentral.com/office/features/online-meetings/video-conferencing.html'}}
URLTextSearcher: Curl command: ['/usr/bin/curl', '--compressed', '--location', 'https://www.ringcentral.com/office/features/online-meetings/video-conferencing.html']
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 658, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 465, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 122, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 109, in re_search
    raise ProcessorError(f"{NO_MATCH_MESSAGE}: {self.env['url']}")
autopkglib.ProcessorError: No match found on URL: https://www.ringcentral.com/office/features/online-meetings/video-conferencing.html
  File "/Library/AutoPkg/autopkglib/__init__.py", line 658, in process
    self.env = processor.process()
No match found on URL: https://www.ringcentral.com/office/features/online-meetings/video-conferencing.html
Failed.
Receipt written to /Users/Shared/autopkg/Cache/local.munki.RingCentralMeetings/receipts/RingCentralMeetings-receipt-20210224-115428.plist

The following recipes failed:
    RingCentralMeetings.munki
        Error in local.munki.RingCentralMeetings: Processor: URLTextSearcher: Error: No match found on URL: https://www.ringcentral.com/office/features/online-meetings/video-conferencing.html

Nothing downloaded, packaged or imported.
```

Is there a reason that this `.pkg` direct-download link link is not being used  => https://app.ringcentral.com/download/RingCentral.pkg

**Comment by homebysix** [comment]
I suspect the pkg URL didn't exist back when the RingCentral recipes were created. I'm open to a PR that uses the URL.

**Comment by blackthroat** [comment]
Fixed with https://github.com/autopkg/homebysix-recipes/pull/384
