### ISSUE TITLE
PureRef.download failing

### ISSUE THREAD

**Issue by gregneagle** [autopkg/homebysix-recipes#608]
PureRef.download is failing to construct a download URL. I suspect it's because the vendor has made it nearly impossible to download without contributing _something_.

Specifically it cannot find what you are calling the "download_key".

I don't see an easy fix, but I didn't spend too long at this.

```
URLTextSearcher
{'Input': {'re_pattern': '<option (selected )?value="([\\d\\.]+)">',
           'result_output_var_name': 'version',
           'url': 'https://www.pureref.com/download.php'}}
URLTextSearcher: Found matching text (version): 1.11.1
{'Output': {'version': '1.11.1'}}
URLTextSearcher
{'Input': {'re_pattern': 'var key = "(.+)";',
           'result_output_var_name': 'download_key',
           'url': 'https://www.pureref.com/download.php'}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 122, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 109, in re_search
    raise ProcessorError(f"{NO_MATCH_MESSAGE}: {self.env['url']}")
autopkglib.ProcessorError: No match found on URL: https://www.pureref.com/download.php
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
No match found on URL: https://www.pureref.com/download.php
```

**Comment by homebysix** [comment]
Just pushed a fix — but admittedly, this is a lot of hoops to jump through so frequently.
